# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scout < Formula
  desc "terminal-native dual-pane file explorer"
  homepage "https://github.com/mirageglobe/scout"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirageglobe/scout/releases/download/v0.5.0/scout_0.5.0_darwin_amd64.tar.gz"
      sha256 "9d870eb05c07cd832f06285a4ca90271a799ffab5f8f888f1cc43557cd1897c4"

      define_method(:install) do
        bin.install "scout"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirageglobe/scout/releases/download/v0.5.0/scout_0.5.0_darwin_arm64.tar.gz"
      sha256 "4de50ce38ad4edfcc5a2d0a51bb7bf790f788e35fbeace84cdb1a03b3bb70b5a"

      define_method(:install) do
        bin.install "scout"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirageglobe/scout/releases/download/v0.5.0/scout_0.5.0_linux_amd64.tar.gz"
      sha256 "65304c0ea67f914b1ff0d9bc868184d01a7fdf31a2f5de067012f35fa3ef0ec9"
      define_method(:install) do
        bin.install "scout"
      end
    end
  end

  test do
    system "#{bin}/scout", "--version"
  end
end
