# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scout < Formula
  desc "terminal-native dual-pane file explorer"
  homepage "https://github.com/mirageglobe/scout"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirageglobe/scout/releases/download/v0.2.0/scout_0.2.0_darwin_amd64.tar.gz"
      sha256 "81fc96a90b76217113ae371f807db62accc347ce8bdc61912595c15d31542086"

      define_method(:install) do
        bin.install "scout"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirageglobe/scout/releases/download/v0.2.0/scout_0.2.0_darwin_arm64.tar.gz"
      sha256 "536dcf20fd563199c800001ef68737277d872a93cc8fe525a00f5affcb1e96e5"

      define_method(:install) do
        bin.install "scout"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirageglobe/scout/releases/download/v0.2.0/scout_0.2.0_linux_amd64.tar.gz"
      sha256 "e3180a7083405253621f22c70c8344d9774c07ed99a11750ec7cf7a3f6724ed1"
      define_method(:install) do
        bin.install "scout"
      end
    end
  end

  test do
    system "#{bin}/scout", "--version"
  end
end
